# https://docs.docker.com/compose/compose-file/
version: '3.7'
services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: "01234"
      POSTGRES_DB: "webge"
    volumes:
      - ./WebGE_database_script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  gramev:
    image: leichen0710/webge
    links:
      - db
    depends_on:
      - db
    ports:
      - 8182:8182
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql:/db:5432/webge"
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: "01234"
    networks:
      - backend


networks:
  backend:
