# https://docs.docker.com/compose/compose-file/
version: '3'
services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: "01234"
      POSTGRES_DB: "webge"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  gramev:
    image: jmcolmenar/webge
    depends_on:
      - db
    ports:
      - 8182:8182
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_DATASOURCE_USERNAME: "usuario"
      SPRING_DATASOURCE_PASSWORD: "01234"
      SPRING_FLYWAY_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_FLYWAY_USER: "usuario"
      SPRING_FLYWAY_PASSWORD: "01234"
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
