# https://docs.docker.com/compose/compose-file/
version: '3.2'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: "01234"
      POSTGRES_DB: "webge"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  gramev:
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"

    depends_on:
      - db
      - rabbitmq
    ports:
      - "8182:8182"
      - "5005:5005"
      - "9010:9010"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_DATASOURCE_USERNAME: "usuario"
      SPRING_DATASOURCE_PASSWORD: "01234"
      SPRING_FLYWAY_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_FLYWAY_USER: "usuario"
      SPRING_FLYWAY_PASSWORD: "01234"
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_LISTENER_SIMPLE_CONCURRENCY: "2"
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
