# https://docs.docker.com/compose/compose-file/
version: '3'
services:
  gramev:
    build:
      context: "../"
      dockerfile: "docker/Dockerfile_debug"

    depends_on:
      - db
    ports:
      - "8182:8182"
      - "5005:5005"
      - "9010:9010"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_DATASOURCE_USERNAME: "usuario"
      SPRING_DATASOURCE_PASSWORD: "01234"
      SPRING_FLYWAY_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_FLYWAY_USER: "usuario"
      SPRING_FLYWAY_PASSWORD: "01234"
    networks:
      - backend
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9010  -Djava.rmi.server.hostname=localhost -jar gramev.jar

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: "01234"
      POSTGRES_DB: "webge"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  pgdata:

networks:
  backend:
