name: Push

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  push-dockerhub:
    name: "Push image to DockerHub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Clean mvn package"
        run: mvn clean package -Dmaven.test.skip=true
      - name: "Build docker image"
        run: docker build -f docker/Dockerfile -t jmcolmenar/webge:latest .
      - name: "Push docker image"
        run: docker push jmcolmenar/webge:latest
      - name: "Build New Release"
        if: github.event_name == 'release'
        run: docker build -f docker/Dockerfile -t jmcolmenar/webge:${{ github.event.release.tag_name }} .
      - name: "Push New Release"
        if: github.event_name == 'release'
        run: docker push jmcolmenar/webge:${{ github.event.release.tag_name }} .
